# print("hello world")
# print("hello python")
# print("---------------------------")

print(" ########### ")
print("#  白日依山尽  #")
print("#  黄河入海流  #")
print("#  欲穷千里目  #")
print("#  白日依山尽  #")
print(" ########### ")